const chapters=[
["Real Numbers","Real numbers include rational and irrational numbers. Euclid's division algorithm uses a=bq+r, where 0≤r<b. The Fundamental Theorem of Arithmetic says every composite number has a unique prime factorisation.","Euclid algorithm • HCF • LCM • Irrational numbers • Fundamental theorem","Find HCF of 135 and 225.","225=135×1+90; 135=90×1+45; 90=45×2+0. Therefore HCF=45.","Always continue Euclid's algorithm until the remainder is zero."],
["Polynomials","A polynomial is an algebraic expression in a variable with non-negative integer powers. For ax²+bx+c, if zeroes are α and β, then α+β=−b/a and αβ=c/a.","Zeroes • Graphs • Relations • Division algorithm","For 2x²−7x+3, find α+β and αβ.","α+β=7/2 and αβ=3/2.","Check the coefficient signs carefully."],
["Pair of Linear Equations","A pair of linear equations can be solved by graphical, substitution, elimination or cross-multiplication methods. For a₁x+b₁y+c₁=0 and a₂x+b₂y+c₂=0, compare the coefficient ratios to determine the number of solutions.","Graphical • Substitution • Elimination • Cross multiplication","Solve 2x+3y=13 and 3x−2y=4.","Multiply to eliminate y: 4x+6y=26 and 9x−6y=12. Adding gives 13x=38, so x=38/13; substitute to get y=31/13.","Write both equations clearly before eliminating a variable."],
["Quadratic Equations","A quadratic equation has the form ax²+bx+c=0, a≠0. Its roots are x=(−b±√(b²−4ac))/2a. The discriminant D=b²−4ac tells whether roots are real and equal, real and distinct, or non-real.","Factorisation • Quadratic formula • Discriminant • Nature of roots","Solve x²−5x+6=0.","x²−5x+6=(x−2)(x−3), so x=2 or 3.","Use factorisation when possible; otherwise use the formula."],
["Arithmetic Progressions","An arithmetic progression has a constant common difference d. The nth term is aₙ=a+(n−1)d. The sum of the first n terms is Sₙ=n/2[2a+(n−1)d].","First term • Common difference • nth term • Sum","Find the 20th term of 3,7,11,...","a=3 and d=4. a₂₀=3+19×4=79.","Identify a, d and n before substituting."],
["Triangles","Two triangles are similar when their corresponding angles are equal and corresponding sides are proportional. Similarity can be established by AA, SSS or SAS. The Basic Proportionality Theorem relates proportional sides when a line is parallel to one side.","Similarity • BPT • Areas • Pythagoras","Similar triangles have corresponding sides in ratio 3:5. Find their area ratio.","Area ratio is the square of side ratio: 3²:5²=9:25.","State the similarity criterion used in a proof."],
["Coordinate Geometry","Distance between two points is √[(x₂−x₁)²+(y₂−y₁)²]. Section formula for internal division in ratio m:n is ((mx₂+nx₁)/(m+n),(my₂+ny₁)/(m+n)).","Distance • Section formula • Midpoint • Area","Find the distance between (−2,3) and (4,−5).","Distance=√(6²+(-8)²)=√100=10.","Keep brackets around negative coordinates."],
["Introduction to Trigonometry","For an acute angle θ in a right triangle: sinθ=P/H, cosθ=B/H, tanθ=P/B. Reciprocal ratios are cosecθ=H/P, secθ=H/B and cotθ=B/P. Important identity: sin²θ+cos²θ=1.","Ratios • Standard angles • Identities • Complementary angles","If sinθ=3/5, find cosθ and tanθ.","Using a 3-4-5 triangle, cosθ=4/5 and tanθ=3/4.","Draw a right triangle when a ratio is given."],
["Applications of Trigonometry","Heights and distances problems use angles of elevation and depression with right triangles. First draw and label the diagram, then select sin, cos or tan.","Elevation • Depression • Heights • Distances","A tower is viewed from a point at distance d with angle of elevation 30°. Express its height h.","tan30°=h/d, so h=d/√3.","A labelled diagram often earns method marks."],
["Circles","A tangent touches a circle at exactly one point. The tangent at any point is perpendicular to the radius through that point. Tangents drawn from an external point are equal.","Tangent-radius theorem • Equal tangents","From P, PA and PB are tangents. If PA=7 cm, find PB.","Tangents from the same external point are equal, so PB=7 cm.","Mention the theorem before applying it."],
["Areas Related to Circles","Area of a circle is πr² and circumference is 2πr. Area of a sector is (θ/360)πr² and arc length is (θ/360)2πr.","Sector • Segment • Arc • Composite figures","Find a 90° sector area for r=7 cm using π=22/7.","(90/360)×22/7×49=38.5 cm².","Use square units for area."],
["Surface Areas & Volumes","Cuboid volume=lbh. Cylinder volume=πr²h. Cone volume=⅓πr²h. Sphere volume=4/3πr³. Hemisphere volume=2/3πr³. Select the correct surface-area or volume formula for the solid.","CSA • TSA • Volume • Combination of solids","Find the volume of a cylinder with r=7 cm and h=10 cm using π=22/7.","V=πr²h=(22/7)×49×10=1540 cm³.","Check whether the question asks curved, total surface area or volume."],
["Statistics","For grouped data, mean can be calculated using direct, assumed-mean or step-deviation methods. Median and mode use the grouped-data formulas with class size h and frequencies.","Mean • Median • Mode • Cumulative frequency","The median class is the class whose cumulative frequency first becomes greater than or equal to n/2.","Then apply Median=l+[(n/2−cf)/f]h.","Make a cumulative-frequency column carefully."],
["Probability","For equally likely outcomes, P(E)=favourable outcomes/total outcomes. Probability lies between 0 and 1. The complement rule is P(not E)=1−P(E).","Sample space • Events • Complement • Classical probability","A die is thrown once. Find P(even) and P(not even).","P(even)=3/6=1/2 and P(not even)=1−1/2=1/2.","List the sample space before counting."]
];
const grid=document.getElementById('chapterGrid');
function renderChapters(list=chapters){grid.innerHTML=list.map((x,i)=>`<button class="chapter" data-i="${chapters.indexOf(x)}"><small>CHAPTER ${chapters.indexOf(x)+1}</small><h3>${x[0]}</h3><p>Notes • Examples • MCQs • Test</p></button>`).join('');document.querySelectorAll('.chapter').forEach(b=>b.onclick=()=>openChapter(+b.dataset.i))}
renderChapters();
function openChapter(i){const x=chapters[i],panel=document.getElementById('chapterPanel');document.getElementById('chapterContent').innerHTML=`
<button class="tab active" onclick="showTab('notes')">Notes</button><button class="tab" onclick="showTab('example')">Solved Example</button><button class="tab" onclick="showTab('practice')">Important Qs</button><button class="tab" onclick="showTab('mcq')">MCQs</button><button class="tab" onclick="showTab('competency')">Competency</button><button class="tab" onclick="showTab('pyq')">PYQ Style</button><button class="tab" onclick="showTab('test')">Chapter Test</button>
<div id="tab-notes" class="tabbody"><small>CHAPTER ${i+1}</small><h2>${x[0]}</h2><h3>📖 Notes</h3><p>${x[1]}</p><h3>🧮 Key topics</h3><p>${x[2]}</p><div class="mini-tip"><b>Exam tip:</b> ${x[5]}</div></div>
<div id="tab-example" class="tabbody" hidden><h3>✏️ Solved Example</h3><p><b>Question:</b> ${x[3]}</p><p><b>Answer / method:</b> ${x[4]}</p></div>
<div id="tab-practice" class="tabbody" hidden><h3>⭐ Important Questions</h3><ol><li>${x[3]}</li><li>State and apply the main theorem/formula from this chapter.</li><li>Solve one exam-style problem and show all steps.</li></ol></div>
<div id="tab-mcq" class="tabbody" hidden><h3>🎯 MCQ Practice</h3><p>Which section should you revise first?</p><button class="option" onclick="this.textContent='✓ Correct: the key formulas and concepts.'">Key formulas</button><button class="option" onclick="this.textContent='Try again — formulas are essential.'">Only answers</button></div>
<div id="tab-competency" class="tabbody" hidden><h3>🧠 Competency-Based</h3><p>A student explains the concept to a friend and then applies it to an unfamiliar situation. Write the steps you would use to solve a new problem from <b>${x[0]}</b>.</p></div>
<div id="tab-pyq" class="tabbody" hidden><h3>📋 PYQ-Style Practice</h3><p>Practise a 3–5 mark question from <b>${x[0]}</b>. Show the formula, substitution, working and final answer with units where applicable.</p></div>
<div id="tab-test" class="tabbody" hidden><h3>📝 Chapter Test</h3><p>1. Define the key concept. 2. Write the main formula/theorem. 3. Solve the solved-example type. 4. Attempt one application question. 5. Check your answer.</p></div>`;panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'start'})}
window.showTab=id=>{document.querySelectorAll('.tabbody').forEach(x=>x.hidden=true);document.getElementById('tab-'+id).hidden=false;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));const btn=[...document.querySelectorAll('.tab')].find(x=>x.getAttribute('onclick')==="showTab('"+id+"')");if(btn)btn.classList.add('active')};
document.getElementById('closeChapter').onclick=()=>document.getElementById('chapterPanel').hidden=true;
const qs=[{q:'If the zeroes of x² − 5x + 6 are α and β, what is α+β?',a:['5','−5','6','−6'],c:0},{q:'What is the value of sin²θ + cos²θ?',a:['0','1','2','sin θ'],c:1},{q:'The distance between (0,0) and (3,4) is:',a:['3','4','5','7'],c:2},{q:'What is the probability of an impossible event?',a:['0','1','1/2','−1'],c:0}];
let qi=0,score=0,answered=false;const qEl=document.getElementById('quizQuestion'),aEl=document.getElementById('answers'),scoreEl=document.getElementById('score');
function render(){answered=false;const x=qs[qi];qEl.textContent=x.q;aEl.innerHTML=x.a.map((a,i)=>`<button class="answer" data-i="${i}">${a}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const i=+b.dataset.i;if(i===x.c){b.classList.add('correct');score++}else{b.classList.add('wrong');document.querySelectorAll('.answer')[x.c].classList.add('correct')}});scoreEl.textContent=`Score: ${score}/${qs.length}`}render();
document.getElementById('next').onclick=()=>{qi=(qi+1)%qs.length;if(qi===0)score=0;render()};
document.getElementById('search').oninput=e=>{const s=e.target.value.toLowerCase();document.querySelectorAll('.resource,.chapter').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(s)?'':'none')};
document.getElementById('theme').onclick=()=>{document.body.classList.toggle('darkmode');document.body.style.background=document.body.classList.contains('darkmode')?'#111522':'var(--bg)';document.body.style.color=document.body.classList.contains('darkmode')?'white':'var(--ink)'};
