const chapters=[
["Real Numbers","Euclid's division lemma: a=bq+r, 0≤r<b. HCF can be found using Euclid's algorithm. Fundamental theorem: every composite number has a unique prime factorisation.","HCF • LCM • Euclid algorithm • Prime factorisation", "Find HCF of 135 and 225.", "225=135×1+90; 135=90×1+45; 90=45×2+0, so HCF=45.", "Use the Euclid algorithm until the remainder becomes 0."],
["Polynomials","A polynomial is an algebraic expression with non-negative integer powers. For ax²+bx+c, if zeroes are α,β: α+β=−b/a and αβ=c/a.","Zeroes • Coefficients • Division algorithm","For 2x²−7x+3, find α+β and αβ.","α+β=7/2 and αβ=3/2.","Remember the signs in the coefficient relations."],
["Pair of Linear Equations","For a₁x+b₁y+c₁=0 and a₂x+b₂y+c₂=0: unique solution if a₁/a₂≠b₁/b₂; infinitely many if all three ratios are equal; no solution if the first two ratios are equal but not the third.","Graphical • Substitution • Elimination • Cross-multiplication","Solve 2x+3y=13 and 3x−2y=4.","Elimination gives x=3 and y=7/3.","Keep signs consistent when multiplying equations."],
["Quadratic Equations","A quadratic equation is ax²+bx+c=0, a≠0. Formula: x=(−b±√(b²−4ac))/2a. D=b²−4ac tells the nature of roots.","Factorisation • Formula • Discriminant • Roots","Solve x²−5x+6=0.","(x−2)(x−3)=0, so x=2,3.","Check the roots by substitution."],
["Arithmetic Progressions","An AP has a constant common difference d. nth term: aₙ=a+(n−1)d. Sum: Sₙ=n/2[2a+(n−1)d].","First term • Common difference • nth term • Sum","Find the 20th term of 3,7,11,...","a=3,d=4, so a₂₀=3+19(4)=79.","Write a, d and n before substituting."],
["Triangles","Similar triangles have equal corresponding angles and proportional corresponding sides. Criteria: AA, SSS, SAS. BPT states a line parallel to one side divides the other sides proportionally.","BPT • Similarity • Areas • Pythagoras","Similar triangles have corresponding sides in ratio 3:5. Find area ratio.","Area ratio is 3²:5²=9:25.","State the similarity criterion before using proportional sides."],
["Coordinate Geometry","Distance: √[(x₂−x₁)²+(y₂−y₁)²]. Section formula: ((mx₂+nx₁)/(m+n),(my₂+ny₁)/(m+n)). Midpoint is the special case m=n.","Distance • Section formula • Midpoint • Area","Find distance between (−2,3) and (4,−5).","√(6²+(−8)²)=√100=10.","Square carefully before adding."],
["Introduction to Trigonometry","sinθ=P/H, cosθ=B/H, tanθ=P/B. Reciprocal ratios: cosecθ=H/P, secθ=H/B, cotθ=B/P. Identity: sin²θ+cos²θ=1.","Ratios • Standard angles • Identities • Complementary angles","If sinθ=3/5 for acute θ, find cosθ and tanθ.","Using a 3-4-5 triangle: cosθ=4/5 and tanθ=3/4.","Draw a right triangle when a ratio is given."],
["Applications of Trigonometry","Heights and distances use right triangles. Angle of elevation is measured upward from the horizontal; angle of depression is measured downward.","Elevation • Depression • Heights • Distances","A tower is viewed at 30°. If horizontal distance is d, write its height h.","tan30°=h/d, so h=d/√3.","Draw and label the figure before calculating."],
["Circles","The tangent at a point is perpendicular to the radius through the point of contact. Tangents from an external point to a circle are equal.","Tangent-radius theorem • Equal tangents","PA and PB are tangents from P. If PA=7 cm, find PB.","PB=PA=7 cm.","Mark the point of contact and radius in geometry proofs."],
["Areas Related to Circles","Circle area=πr²; circumference=2πr. Sector area=(θ/360)πr²; arc length=(θ/360)2πr.","Sector • Segment • Arc length • Composite figures","Find a 90° sector area for r=7 cm, π=22/7.","(90/360)×22/7×49=38.5 cm².","Keep units squared for area and linear for arc length."],
["Surface Areas & Volumes","Cuboid V=lbh. Cylinder V=πr²h. Cone V=⅓πr²h. Sphere V=4/3πr³. Hemisphere V=2/3πr³.","CSA • TSA • Volume • Combination of solids","Find cylinder volume for r=7 cm,h=10 cm, π=22/7.","V=(22/7)×49×10=1540 cm³.","Check whether the question asks CSA, TSA or volume."],
["Statistics","Grouped-data mean can use direct, assumed-mean or step-deviation methods. Median = l+[(n/2−cf)/f]h. Mode = l+[(f₁−f₀)/(2f₁−f₀−f₂)]h.","Mean • Median • Mode • Cumulative frequency","Identify the median class before applying the grouped-data median formula.","Median class is the class whose cumulative frequency first exceeds n/2.","Write the formula and define each symbol."],
["Probability","For equally likely outcomes, P(E)=favourable outcomes/total outcomes. 0≤P(E)≤1 and P(not E)=1−P(E).","Events • Classical probability • Complement","A die is thrown once. Find P(even) and P(not even).","P(even)=3/6=1/2; P(not even)=1/2.","List the sample space before counting outcomes."]
];
const grid=document.getElementById('chapterGrid');
function renderChapters(list=chapters){grid.innerHTML=list.map((x,i)=>`<button class="chapter" data-i="${chapters.indexOf(x)}"><small>CHAPTER ${chapters.indexOf(x)+1}</small><h3>${x[0]}</h3><p>Notes • Examples • MCQs • Test</p></button>`).join('');document.querySelectorAll('.chapter').forEach(b=>b.onclick=()=>openChapter(+b.dataset.i))}
renderChapters();
function openChapter(i){const x=chapters[i],panel=document.getElementById('chapterPanel');document.getElementById('chapterContent').innerHTML=`
<button class="tab active" onclick="showTab('notes')">Notes</button><button class="tab" onclick="showTab('example')">Solved Example</button><button class="tab" onclick="showTab('practice')">Important Qs</button><button class="tab" onclick="showTab('mcq')">MCQs</button><button class="tab" onclick="showTab('competency')">Competency</button><button class="tab" onclick="showTab('pyq')">PYQ Style</button><button class="tab" onclick="showTab('test')">Chapter Test</button>
<div id="tab-notes" class="tabbody"><small>CHAPTER ${i+1}</small><h2>${x[0]}</h2><h3>📖 Notes</h3><p>${x[1]}</p><h3>🧮 Key topics</h3><p>${x[2]}</p><div class="mini-tip"><b>Exam tip:</b> ${x[5]}</div></div>
<div id="tab-example" class="tabbody" hidden><h3>✏️ Solved Example</h3><p><b>Question:</b> ${x[3]}</p><p><b>Answer / method:</b> ${x[4]}</p></div>
<div id="tab-practice" class="tabbody" hidden><h3>⭐ Important Questions</h3><ol><li>${x[3]}</li><li>State and apply the main theorem/formula from this chapter.</li><li>Solve one exam-style problem and show all steps.</li></ol></div>
<div id="tab-mcq" class="tabbody" hidden><h3>🎯 MCQ Practice</h3><p>Which section should you revise first?</p><button class="option" onclick="this.textContent='✓ Correct: the key formulas and concepts.'">Key formulas</button><button class="option" onclick="this.textContent='Try again — formulas are essential.'">Only answers</button></div>
<div id="tab-competency" class="tabbody" hidden><h3>🧠 Competency-Based</h3><p>A student explains the concept to a friend and then applies it to an unfamiliar situation. Write the steps you would use to solve a new problem from <b>${x[0]}</b>.</p></div>
<div id="tab-pyq" class="tabbody" hidden><h3>📋 PYQ-Style Practice</h3><p>Practise a 3–5 mark question from <b>${x[0]}</b>. Show the formula, substitution, working and final answer with units where applicable.</p></div>
<div id="tab-test" class="tabbody" hidden><h3>📝 Chapter Test</h3><p>1. Define the key concept. 2. Write the main formula/theorem. 3. Solve the solved-example type. 4. Attempt one application question. 5. Check your answer.</p></div>`;panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'start'})}
window.showTab=id=>{document.querySelectorAll('.tabbody').forEach(x=>x.hidden=true);document.getElementById('tab-'+id).hidden=false;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));event.target.classList.add('active')};
document.getElementById('closeChapter').onclick=()=>document.getElementById('chapterPanel').hidden=true;
const qs=[{q:'If the zeroes of x² − 5x + 6 are α and β, what is α+β?',a:['5','−5','6','−6'],c:0},{q:'What is the value of sin²θ + cos²θ?',a:['0','1','2','sin θ'],c:1},{q:'The distance between (0,0) and (3,4) is:',a:['3','4','5','7'],c:2},{q:'What is the probability of an impossible event?',a:['0','1','1/2','−1'],c:0}];
let qi=0,score=0,answered=false;const qEl=document.getElementById('quizQuestion'),aEl=document.getElementById('answers'),scoreEl=document.getElementById('score');
function render(){answered=false;const x=qs[qi];qEl.textContent=x.q;aEl.innerHTML=x.a.map((a,i)=>`<button class="answer" data-i="${i}">${a}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const i=+b.dataset.i;if(i===x.c){b.classList.add('correct');score++}else{b.classList.add('wrong');document.querySelectorAll('.answer')[x.c].classList.add('correct')}});scoreEl.textContent=`Score: ${score}/${qs.length}`}render();
document.getElementById('next').onclick=()=>{qi=(qi+1)%qs.length;if(qi===0)score=0;render()};
document.getElementById('search').oninput=e=>{const s=e.target.value.toLowerCase();document.querySelectorAll('.resource,.chapter').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(s)?'':'none')};
document.getElementById('theme').onclick=()=>{document.body.classList.toggle('darkmode');document.body.style.background=document.body.classList.contains('darkmode')?'#111522':'var(--bg)';document.body.style.color=document.body.classList.contains('darkmode')?'white':'var(--ink)'};
